const data = [
  {
    id: 1,
    name: "RCE-Theatres - 907 S Backend Dr Handerson, NC 27356",
    city: "London",
    location: "8558 Pecan St",
    price: "7255",
    room: 3,
    bed: 4,
    bath: 1,
    sft: 732,
    image: "/assets/rav4.avif",
  },
  {
    id: 2,
    name: "London Luxury Apartment - 123 Main St",
    city: "London",
    location: "456 Elm St",
    price: "9000",
    room: 2,
    bed: 2,
    bath: 2,
    sft: 1000,
    image: "/assets/london-apartment.avif",
  },
  {
    id: 3,
    name: "Downtown London Loft - 789 Oak St",
    city: "London",
    location: "789 Oak St",
    price: "6000",
    room: 1,
    bed: 1,
    bath: 1,
    sft: 500,
    image: "/assets/london-loft.avif",
  },
  {
    id: 4,
    name: "London Townhouse - 567 Maple St",
    city: "London",
    location: "567 Maple St",
    price: "8500",
    room: 4,
    bed: 3,
    bath: 2,
    sft: 1200,
    image: "/assets/london-townhouse.avif",
  },
  {
    id: 5,
    name: "Cozy London Cottage - 789 Elmwood Ave",
    city: "London",
    location: "789 Elmwood Ave",
    price: "5500",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 800,
    image: "/assets/london-cottage.avif",
  },
  {
    id: 6,
    name: "Modern London Condo - 123 Oakwood Dr",
    city: "London",
    location: "123 Oakwood Dr",
    price: "7500",
    room: 2,
    bed: 2,
    bath: 2,
    sft: 1000,
    image: "/assets/london-condo.avif",
  },
  {
    id: 7,
    name: "Spacious London Villa - 456 Maplewood Ln",
    city: "London",
    location: "456 Maplewood Ln",
    price: "11000",
    room: 5,
    bed: 4,
    bath: 3,
    sft: 1800,
    image: "/assets/london-villa.avif",
  },
  {
    id: 8,
    name: "Charming London Bungalow - 789 Cedar Ave",
    city: "London",
    location: "789 Cedar Ave",
    price: "4500",
    room: 1,
    bed: 1,
    bath: 1,
    sft: 600,
    image: "/assets/london-bungalow.avif",
  },
  {
    id: 9,
    name: "Elegant London Mansion - 1010 Oak Lane",
    city: "London",
    location: "1010 Oak Lane",
    price: "15000",
    room: 6,
    bed: 5,
    bath: 4,
    sft: 2500,
    image: "/assets/london-mansion.avif",
  },
  {
    id: 10,
    name: "London Suburban House - 321 Maple St",
    city: "London",
    location: "321 Maple St",
    price: "8000",
    room: 4,
    bed: 3,
    bath: 2,
    sft: 1200,
    image: "/assets/london-house.avif",
  },
  {
    id: 11,
    name: "Eiffel Tower View Apartment - 123 Rue de Paris",
    city: "Paris",
    location: "123 Rue de Paris",
    price: "10000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1100,
    image: "/assets/paris-apartment.avif",
  },
  {
    id: 12,
    name: "Chic Parisian Loft - 456 Avenue des Arts",
    city: "Paris",
    location: "456 Avenue des Arts",
    price: "8500",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 900,
    image: "/assets/paris-loft.avif",
  },
  {
    id: 13,
    name: "Montmartre Studio - 789 Rue du Moulin",
    city: "Paris",
    location: "789 Rue du Moulin",
    price: "6000",
    room: 1,
    bed: 1,
    bath: 1,
    sft: 500,
    image: "/assets/paris-studio.avif",
  },
  {
    id: 14,
    name: "Luxury Paris Villa - 567 Boulevard Parisien",
    city: "Paris",
    location: "567 Boulevard Parisien",
    price: "15000",
    room: 5,
    bed: 4,
    bath: 3,
    sft: 1800,
    image: "/assets/paris-villa.avif",
  },
  {
    id: 15,
    name: "Cozy Parisian Cottage - 789 Rue de la Seine",
    city: "Paris",
    location: "789 Rue de la Seine",
    price: "5500",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 700,
    image: "/assets/paris-cottage.avif",
  },
  {
    id: 16,
    name: "Modern Paris Condo - 123 Avenue de la Liberté",
    city: "Paris",
    location: "123 Avenue de la Liberté",
    price: "7500",
    room: 2,
    bed: 2,
    bath: 2,
    sft: 950,
    image: "/assets/paris-condo.avif",
  },
  {
    id: 17,
    name: "Elegant Paris Mansion - 1010 Champs-Élysées",
    city: "Paris",
    location: "1010 Champs-Élysées",
    price: "20000",
    room: 6,
    bed: 5,
    bath: 4,
    sft: 2800,
    image: "/assets/paris-mansion.avif",
  },
  {
    id: 18,
    name: "Paris Suburban House - 321 Avenue de la Campagne",
    city: "Paris",
    location: "321 Avenue de la Campagne",
    price: "8000",
    room: 4,
    bed: 3,
    bath: 2,
    sft: 1200,
    image: "/assets/paris-house.avif",
  },
  {
    id: 19,
    name: "Seine River View Apartment - 555 Quai des Orfèvres",
    city: "Paris",
    location: "555 Quai des Orfèvres",
    price: "11000",
    room: 4,
    bed: 2,
    bath: 2,
    sft: 1500,
    image: "/assets/paris-river-view.avif",
  },
  {
    id: 20,
    name: "Historic Paris Townhouse - 789 Rue Saint-Antoine",
    city: "Paris",
    location: "789 Rue Saint-Antoine",
    price: "9000",
    room: 3,
    bed: 3,
    bath: 2,
    sft: 1300,
    image: "/assets/paris-townhouse.avif",
  },
  {
    id: 21,
    name: "Luxury Mumbai Apartment - 123 Marine Drive",
    city: "Mumbai",
    location: "123 Marine Drive",
    price: "12000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1200,
    image: "/assets/mumbai-apartment.avif",
  },
  {
    id: 22,
    name: "Mumbai Beachfront Villa - 456 Juhu Beach",
    city: "Mumbai",
    location: "456 Juhu Beach",
    price: "18000",
    room: 4,
    bed: 3,
    bath: 3,
    sft: 2200,
    image: "/assets/mumbai-villa.avif",
  },
  {
    id: 23,
    name: "Downtown Mumbai Loft - 789 Nariman Point",
    city: "Mumbai",
    location: "789 Nariman Point",
    price: "9000",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 1000,
    image: "/assets/mumbai-loft.avif",
  },
  {
    id: 24,
    name: "Cozy Mumbai Cottage - 567 Bandra",
    city: "Mumbai",
    location: "567 Bandra",
    price: "7500",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 800,
    image: "/assets/mumbai-cottage.avif",
  },
  {
    id: 25,
    name: "Modern Mumbai Condo - 123 Worli",
    city: "Mumbai",
    location: "123 Worli",
    price: "9500",
    room: 2,
    bed: 2,
    bath: 2,
    sft: 1100,
    image: "/assets/mumbai-condo.avif",
  },
  {
    id: 26,
    name: "Elegant Mumbai Mansion - 1010 Malabar Hill",
    city: "Mumbai",
    location: "1010 Malabar Hill",
    price: "25000",
    room: 5,
    bed: 4,
    bath: 4,
    sft: 3000,
    image: "/assets/mumbai-mansion.avif",
  },
  {
    id: 27,
    name: "Mumbai Suburban House - 321 Andheri",
    city: "Mumbai",
    location: "321 Andheri",
    price: "8000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1200,
    image: "/assets/mumbai-house.avif",
  },
  {
    id: 28,
    name: "Seaview Apartment - 555 Versova",
    city: "Mumbai",
    location: "555 Versova",
    price: "13000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1400,
    image: "/assets/mumbai-seaview.avif",
  },
  {
    id: 29,
    name: "Mumbai Skyline Penthouse - 789 Lower Parel",
    city: "Mumbai",
    location: "789 Lower Parel",
    price: "28000",
    room: 4,
    bed: 3,
    bath: 3,
    sft: 2400,
    image: "/assets/mumbai-penthouse.avif",
  },
  {
    id: 30,
    name: "Historic Mumbai Townhouse - 789 Colaba",
    city: "Mumbai",
    location: "789 Colaba",
    price: "11000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1600,
    image: "/assets/mumbai-townhouse.avif",
  },
  {
    id: 31,
    name: "New York City Apartment - 123 Broadway",
    city: "New York",
    location: "123 Broadway",
    price: "18000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1200,
    image: "/assets/new-york-apartment.avif",
  },
  {
    id: 32,
    name: "Luxury New York Brownstone - 456 Park Avenue",
    city: "New York",
    location: "456 Park Avenue",
    price: "25000",
    room: 4,
    bed: 3,
    bath: 3,
    sft: 2200,
    image: "/assets/new-york-brownstone.avif",
  },
  {
    id: 33,
    name: "Downtown New York Loft - 789 Soho",
    city: "New York",
    location: "789 Soho",
    price: "12000",
    room: 2,
    bed: 1,
    bath: 1,
    sft: 1000,
    image: "/assets/new-york-loft.avif",
  },
  {
    id: 34,
    name: "Cozy New York Studio - 567 East Village",
    city: "New York",
    location: "567 East Village",
    price: "7500",
    room: 1,
    bed: 1,
    bath: 1,
    sft: 600,
    image: "/assets/new-york-studio.avif",
  },
  {
    id: 35,
    name: "Modern New York Condo - 123 Tribeca",
    city: "New York",
    location: "123 Tribeca",
    price: "9500",
    room: 2,
    bed: 2,
    bath: 2,
    sft: 1100,
    image: "/assets/new-york-condo.avif",
  },
  {
    id: 36,
    name: "Elegant New York Mansion - 1010 Upper East Side",
    city: "New York",
    location: "1010 Upper East Side",
    price: "35000",
    room: 5,
    bed: 4,
    bath: 4,
    sft: 3200,
    image: "/assets/new-york-mansion.avif",
  },
  {
    id: 37,
    name: "New York Suburban House - 321 Westchester",
    city: "New York",
    location: "321 Westchester",
    price: "12000",
    room: 4,
    bed: 3,
    bath: 2,
    sft: 1800,
    image: "/assets/new-york-house.avif",
  },
  {
    id: 38,
    name: "Central Park View Apartment - 555 Central Park West",
    city: "New York",
    location: "555 Central Park West",
    price: "22000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1400,
    image: "/assets/new-york-central-park.avif",
  },
  {
    id: 39,
    name: "New York City Skyline Penthouse - 789 Wall Street",
    city: "New York",
    location: "789 Wall Street",
    price: "45000",
    room: 4,
    bed: 3,
    bath: 3,
    sft: 2400,
    image: "/assets/new-york-penthouse.avif",
  },
  {
    id: 40,
    name: "Historic New York Townhouse - 789 Greenwich Village",
    city: "New York",
    location: "789 Greenwich Village",
    price: "18000",
    room: 3,
    bed: 2,
    bath: 2,
    sft: 1600,
    image: "/assets/new-york-townhouse.avif",
  },
];

export default data;
