const data = [
    {
      id: 1,
      name: "Toyota RAV4",
      year: 2021,
      price: "222",
      capacity: 4,
      type: "hybrid",
      fuel: "6.1km/1 litre",
      mode: "Automa",
      image: "/assets/rav4.avif",
    },
    {
      id: 2,
      name: "Honda Civic",
      year: 2022,
      price: "200",
      capacity: 5,
      type: "gasoline",
      fuel: "7.0km/1 litre",
      mode: "Manual",
      image: "/assets/civic.webp",
    },
    {
      id: 3,
      name: "Ford Escape",
      year: 2020,
      price: "240",
      capacity: 5,
      type: "hybrid",
      fuel: "5.5km/1 litre",
      mode: "Automa",
      image: "/assets/ford.avif",
    },
    {
      id: 4,
      name: "Chevrolet Equinox",
      year: 2022,
      price: "215",
      capacity: 5,
      type: "gasoline",
      fuel: "6.5km/1 litre",
      mode: "Automa",
      image: "/assets/equinox.jpg",
    },
    {
      id: 5,
      name: "Nissan Rogue",
      year: 2023,
      price: "230",
      capacity: 5,
      type: "hybrid",
      fuel: "5.8km/1 litre",
      mode: "Automa",
      image: "/assets/rogue.jpg",
    },
    {
      id: 6,
      name: "Mazda CX-5",
      year: 2021,
      price: "210",
      capacity: 4,
      type: "gasoline",
      fuel: "6.8km/1 litre",
      mode: "Manual",
      image: "/assets/mazda.jpeg",
    },
    {
      id: 7,
      name: "Subaru Outback",
      year: 2023,
      price: "245",
      capacity: 5,
      type: "hybrid",
      fuel: "5.6km/1 litre",
      mode: "Automa",
      image: "/assets/subaru.jpg",
    },
    {
      id: 8,
      name: "Jeep Cherokee",
      year: 2022,
      price: "225",
      capacity: 5,
      type: "gasoline",
      fuel: "6.4km/1 litre",
      mode: "Automa",
      image: "/assets/jeep.jpg",
    },
    {
      id: 9,
      name: "Kia Sportage",
      year: 2021,
      price: "200",
      capacity: 5,
      type: "hybrid",
      fuel: "6.0km/1 litre",
      mode: "Automa",
      image: "/assets/kia.png",
    },
    {
      id: 10,
      name: "Hyundai Tucson",
      year: 2023,
      price: "235",
      capacity: 5,
      type: "gasoline",
      fuel: "6.7km/1 litre",
      mode: "Automa",
      image: "/assets/tucson.jpg",
    },
    {
      id: 11,
      name: "Volkswagen Golf",
      year: 2022,
      price: "210",
      capacity: 5,
      type: "gasoline",
      fuel: "6.2km/1 litre",
      mode: "Manual",
      image: "/assets/golf.jpg",
    },
    {
      id: 12,
      name: "Audi Q5",
      year: 2023,
      price: "255",
      capacity: 5,
      type: "hybrid",
      fuel: "5.7km/1 litre",
      mode: "Automa",
      image: "/assets/audi.jpg",
    },
    {
      id: 13,
      name: "Mercedes-Benz C-Class",
      year: 2022,
      price: "280",
      capacity: 4,
      type: "gasoline",
      fuel: "6.5km/1 litre",
      mode: "Automa",
      image: "/assets/mercedes.jpg",
    },
    {
      id: 14,
      name: "BMW X3",
      year: 2023,
      price: "270",
      capacity: 5,
      type: "hybrid",
      fuel: "5.9km/1 litre",
      mode: "Automa",
      image: "/assets/bmw.jpg",
    },
    {
      id: 15,
      name: "Lexus RX",
      year: 2021,
      price: "290",
      capacity: 5,
      type: "hybrid",
      fuel: "5.4km/1 litre",
      mode: "Automa",
      image: "/assets/lexus.jpg",
    },
    {
      id: 16,
      name: "Tesla Model 3",
      year: 2022,
      price: "400",
      capacity: 5,
      type: "electric",
      fuel: "0.0km/1 litre",
      mode: "Automa",
      image: "/assets/tesla.jpg",
    },
    {
      id: 17,
      name: "Porsche Cayenne",
      year: 2023,
      price: "350",
      capacity: 5,
      type: "hybrid",
      fuel: "5.8km/1 litre",
      mode: "Automa",
      image: "/assets/porsche.jpg",
    },
    {
      id: 18,
      name: "Land Rover Discovery",
      year: 2022,
      price: "275",
      capacity: 7,
      type: "gasoline",
      fuel: "7.2km/1 litre",
      mode: "Automa",
      image: "/assets/landrover.jpg",
    },
    {
      id: 19,
      name: "Volvo XC60",
      year: 2021,
      price: "265",
      capacity: 5,
      type: "hybrid",
      fuel: "5.6km/1 litre",
      mode: "Automa",
      image: "/assets/volvo.jpg",
    },
    {
      id: 20,
      name: "Mitsubishi Outlander",
      year: 2022,
      price: "215",
      capacity: 7,
      type: "hybrid",
      fuel: "5.9km/1 litre",
      mode: "Automa",
      image: "/assets/mitsubishi.jpg",
    },
  ];
  
  export default data;
  