const data = [
    {
        id: 1,
        name: "RCE-Theatres - 907 S Backend Dr Handerson, NC 27356",
        city: "London",
        location: "8558 Pecan St",
        price: "7255",
        room: 3,
        bed: 4,
        bath: 1,
        sft: 732,
        image: "/assets/rav4.avif",
      },
      {
        id: 2,
        name: "London Luxury Apartment - 123 Main St",
        city: "London",
        location: "456 Elm St",
        price: "9000",
        room: 2,
        bed: 2,
        bath: 2,
        sft: 1000,
        image: "/assets/london-apartment.avif",
      },
      {
        id: 3,
        name: "Downtown London Loft - 789 Oak St",
        city: "London",
        location: "789 Oak St",
        price: "6000",
        room: 1,
        bed: 1,
        bath: 1,
        sft: 500,
        image: "/assets/london-loft.avif",
      },
      {
        id: 4,
        name: "London Townhouse - 567 Maple St",
        city: "London",
        location: "567 Maple St",
        price: "8500",
        room: 4,
        bed: 3,
        bath: 2,
        sft: 1200,
        image: "/assets/london-townhouse.avif",
      },
      {
        id: 5,
        name: "Cozy London Cottage - 789 Elmwood Ave",
        city: "London",
        location: "789 Elmwood Ave",
        price: "5500",
        room: 2,
        bed: 1,
        bath: 1,
        sft: 800,
        image: "/assets/london-cottage.avif",
      },
      {
        id: 6,
        name: "Modern London Condo - 123 Oakwood Dr",
        city: "London",
        location: "123 Oakwood Dr",
        price: "7500",
        room: 2,
        bed: 2,
        bath: 2,
        sft: 1000,
        image: "/assets/london-condo.avif",
      },
      {
        id: 7,
        name: "Spacious London Villa - 456 Maplewood Ln",
        city: "London",
        location: "456 Maplewood Ln",
        price: "11000",
        room: 5,
        bed: 4,
        bath: 3,
        sft: 1800,
        image: "/assets/london-villa.avif",
      },
      {
        id: 8,
        name: "Charming London Bungalow - 789 Cedar Ave",
        city: "London",
        location: "789 Cedar Ave",
        price: "4500",
        room: 1,
        bed: 1,
        bath: 1,
        sft: 600,
        image: "/assets/london-bungalow.avif",
      },
      {
        id: 9,
        name: "Elegant London Mansion - 1010 Oak Lane",
        city: "London",
        location: "1010 Oak Lane",
        price: "15000",
        room: 6,
        bed: 5,
        bath: 4,
        sft: 2500,
        image: "/assets/london-mansion.avif",
      },
      {
        id: 10,
        name: "London Suburban House - 321 Maple St",
        city: "London",
        location: "321 Maple St",
        price: "8000",
        room: 4,
        bed: 3,
        bath: 2,
        sft: 1200,
        image: "/assets/london-house.avif",
      },
  ];
  
  export default data;
  